### ISSUE TITLE
Need More Details of How to use?

### ISSUE THREAD

**Issue by code-masala** [sionzee/rollup-plugin-inline-svg#13]
@sionzee  I try to integrate this in sveltekit for inline svg.
But for option part didn't get much info?
All svg brokes after using it.
Can you provide into the details for the community?

**Comment by sionzee** [comment]
@code-masala sorry for late response, could you provide more into on all broken svgs?

Actually you just have to install the package and put it into `plugins` field in the rollup.config.js

i.e.:
```javascript
import inlineSvg from 'rollup-plugin-inline-svg';
export default {
  input: "src/input.js",
  output: "dist/output.js",
  plugins: [inlineSvg()]
}
```

And then you can include your svg anywhere in the code processed by rollup. 
i.e.: whatever.mjs
```javascript
import UserSvg from "../icons/user.svg"

console.log(UserSvg); // will print content of the svg
document.getElementById("user-icon").innerHTML = UserSvg;

```
