### ISSUE TITLE
Set sensible default for include

### ISSUE THREAD

**Issue by Frank3K** [sionzee/rollup-plugin-inline-svg#19]
Thanks for updating this plugin to TS.

According to the [current changelog](https://github.com/sionzee/rollup-plugin-inline-svg/blob/a95f1c9e93ed2044913fd7f4bb114e7151402cc5/CHANGELOG.md) the default for `include` is `['*.svg']`. According to the code the default is `['*.ts', '*.js']`:

https://github.com/sionzee/rollup-plugin-inline-svg/blob/a95f1c9e93ed2044913fd7f4bb114e7151402cc5/src/index.ts#L6

I don't understand the latter default.

Just `['*.svg']` is OK, but I think `['**/*.svg']` makes more sense, otherwise only files in the root directory are processed.

**Comment by sionzee** [comment]
Hi @Frank3K, I partially agree with you. 

~The correct variant is `**/*.ts`. The `include` option is a filter for files that will be transformed. For example, where to look for the .svg imports and replace them with inlined content.~

I will update the changelog and fix the default value to default to ~`**/*.ts` + `**/*.js`~

// Edit (based on feedback from comments below)

The filter looks for SVG files and then replaces them with valid javascript modules. So the correct value is `**/*.svg`

**Comment by Frank3K** [comment]
Thanks for your fast reply. 

I'm not sure I understand how the `include` should be used. When I override it (such that the default is not used), it throws. Configuration:

```js
			InlineSvg({
				include: ['**/*.ts', '**/*.js'],
			}),
```

Error

```
Error: rollup-plugin-inline-svg: file <some-path>\index.ts is not a valid svg. The root element is not a svg tag.
```

I does not throw if I use `include: ['*.svg']`. I can see (after adding some logging) that my imported SVG files are getting processed.

**Comment by sionzee** [comment]
I was wrong, and you are right 👍 . I reviewed the code, and it is supposed to replace .svg files for modules. I would notice it during coding and probably get back here with apologies and a fix. 

Your code:
```typescript
InlineSvg({
  include: ['**/*.svg'],
}),
```
is definitely right and I'm sorry for the confusion.

**Comment by sionzee** [comment]
Hi @Frank3K,

I fixed all your reported issues in 3.0.1.

Thank you for reporting the issues, and I hope it will resolve all your problems.
I wish you happy coding.

**Comment by Frank3K** [comment]
@sionzee Thanks for fixing. Could it be that the new code is not present in the npm package? It looks like it contains the compiled old code.

**Comment by sionzee** [comment]
@Frank3K It seems you are right. Weird, I will rebuild it and release it as 3.0.2 in a few minutes.
