### ISSUE TITLE
Multi-line SVG is not exported correctly

### ISSUE THREAD

**Issue by Frank3K** [sionzee/rollup-plugin-inline-svg#21]
The exported SVG is exported using single quotes, but this generates invalid JavaScript code when the SVG file contains more than a single line. Backticks could be used instead, or newlines can be stripped.

https://github.com/sionzee/rollup-plugin-inline-svg/blob/a95f1c9e93ed2044913fd7f4bb114e7151402cc5/src/index.ts#L18

**Comment by sionzee** [comment]
Hi, backticks would break compatibility with the IE11. https://github.com/sionzee/rollup-plugin-inline-svg/pull/4

Stripping the new lines makes sense, and I would go for that option.
