### ISSUE TITLE
SVG validation still too string

### ISSUE THREAD

**Issue by acarl005** [sionzee/rollup-plugin-inline-svg#27]
![test-table](https://user-images.githubusercontent.com/8334252/171968066-e88a593d-ce8f-4c30-b44e-ae4051549602.svg)

This is a valid SVG which is failing validation

```
rollup-plugin-inline-svg: file /path/totest-table.svg is not a valid svg. The 'svg' node was not found.
```

**Comment by sionzee** [comment]
@acarl005 Are you using the latest version? I have tried running the SVG file and it parsed it with no problems.

Please ensure that you are running the latest version by viewing the package in node_modules and looking for the package.json file.

You should see
```
"version": "3.0.3",
```

**Comment by acarl005** [comment]
Weird. Somehow a fresh `npm i -D rollup-plugin-inline-svg` gave me version `^1.0.0-beta.6`. 🤷‍♂️
Switching to latest version fixed it. Thanks!
